version: '3.8'

services:
    mem0-mcp:
        build:
            context: .
            dockerfile: Dockerfile
        # Define container name for easier reference
        container_name: mem0-mcp
        ports:
            # Map port 8080 to access the MCP server from the host
            - '8080:8080'
            # Map port 4040 to access the ngrok web interface (http://localhost:4040)
            - '4040:4040'
        volumes:
            # Volume for persistent data storage (optional)
            - ./data:/app/data
        environment:
            # Required environment variables
            - MEM0_API_KEY=${MEM0_API_KEY}
            # If NGROK_AUTHTOKEN is provided, ngrok will automatically create a tunnel
            - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN:-}
            - HOST=0.0.0.0
            - PORT=8080
            - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
        restart: unless-stopped
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 10s
